Work_Source/Controllers/OfertasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Work_Source.Models;
using PagedList;

namespace Work_Source.Controllers
{
    public class OfertasController : Controller
    {
        OfertasEmpleoModel model = new OfertasEmpleoModel();
        PerfilContratacionModel perfilModel = new PerfilContratacionModel();
        PonderacionCriteriosModel ponderacionModel = new PonderacionCriteriosModel();
        CriteriosEvaluacionModel criteriosModel = new CriteriosEvaluacionModel();
        BolsaTrabajoGOESEntities ctx = new BolsaTrabajoGOESEntities();
        // GET: Ofertas
        public ViewResult Index(string filtroBusqueda, string busqueda,string busqueda2, int? page)
        {
            page = 1;
            var ofertas = model.Listar();

            if (!string.IsNullOrEmpty(filtroBusqueda) && !string.IsNullOrEmpty(busqueda))
            {
                switch (filtroBusqueda)
                {
                    case "Todos":
                        ofertas = model.Listar();
                        break;
                    case "Nombre":
                        ofertas = from o in ctx.OfertasEmpleo
                                    where o.NombreOferta.Contains(busqueda)
                                    orderby o.NombreOferta
                                    select o;
                        break;

                    case "Creador":
                        ofertas = from o in ctx.OfertasEmpleo
                                  where o.creador == busqueda
                                  orderby o.fecha_inicio descending
                                  select o;
                        break;

                    case "Estado":
                        int estado = int.Parse(busqueda);
                        ofertas = from o in ctx.OfertasEmpleo
                                  where o.estado == estado
                                  orderby o.fecha_inicio descending
                                  select o;
                        break;

                    case "Fechas":
                        if (!string.IsNullOrEmpty(busqueda2))
                        {
                            DateTime fechaI = DateTime.Parse(busqueda);
                            DateTime fechaF = DateTime.Parse(busqueda2);

                            ofertas = from o in ctx.OfertasEmpleo
                                      where o.fecha_inicio >= fechaI && o.fecha_inicio <= fechaF
                                      orderby o.fecha_inicio descending
                                      select o;
                        }
                        break;
                }
            }

            ViewBag.ValorOculto = filtroBusqueda;
            ViewBag.Busqueda = busqueda + "/" + busqueda2;
            ViewBag.ListadoCreadores = new SelectList(model.CreadoresDeOfertas(), "codigo", "nombres");

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (ofertas.Count() == 0)
            {
                TempData["errorMessage"] = "No se encontraron resultados en su búsqueda";
            }

            return View(ofertas.ToPagedList(pageNumber, pageSize));
        }

        // GET: Ofertas/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                TempData["errorMessage"] = "Seleccione la oferta de la cual desea visualizar detalles";
                return RedirectToAction("Index");
            }

            OfertasEmpleo o = model.GetById(id);

            if(o == null)
            {
                TempData["errorMessage"] = "No se encontró el registro de la oferta que solicitó";
                return RedirectToAction("Index");
            }

            return View(o);
        }

        // GET: Ofertas/Create
        public ActionResult Create()
        {
            ViewBag.Criterios = criteriosModel.List();
            return View();
        }

        // POST: Ofertas/Create
        [HttpPost]
        public ActionResult Create(OfertaEmpleoCompleta oferta, string[] criterios)
        {
            int result1 = 0;
            int result2 = 0;
            int result3 = 0;
            ViewBag.Criterios = criteriosModel.List();
            try
            {
                if (ModelState.IsValid)
                {
                    if((decimal.Parse(criterios[0]) + decimal.Parse(criterios[1]) + decimal.Parse(criterios[2]) + decimal.Parse(criterios[3])) != 100)
                    {
                        ViewBag.ErrorPonderacion = "La suma de las ponderaciones de los criterios debe ser igual al 100%";
                        return View(oferta);
                    }

                    if(oferta.InformacionOferta.fecha_fin <= oferta.InformacionOferta.fecha_inicio)
                    {
                        ViewBag.ErrorFechas = "La Fecha de finalización debe ser mayor a la fecha de paertura de la oferta";
                        return View(oferta);
                    }

                    //Completando datos de la clase OfertaEmpleo
                    oferta.InformacionOferta.IdOferta = model.CodigoOfertaEmpleo();
                    oferta.InformacionOferta.creador = "LA78906578";
                    result1 = model.Insert(oferta.InformacionOferta);

                    //Completando datos de la clase PerfilContratacion
                    oferta.InformacionPerfilContratacion.IdOferta = oferta.InformacionOferta.IdOferta;
                    result2 = perfilModel.Insert(oferta.InformacionPerfilContratacion);

                    //Completando información de la clase Ponderacion_Criterios

                    Ponderacion_Criterios criterio1 = new Ponderacion_Criterios
                    {
                        IdOferta = oferta.InformacionOferta.IdOferta,
                        IdCriterio = 1,
                        Ponderacion = decimal.Parse(criterios[0])
                    };

                    Ponderacion_Criterios criterio2 = new Ponderacion_Criterios
                    {
                        IdOferta = oferta.InformacionOferta.IdOferta,
                        IdCriterio = 2,
                        Ponderacion = decimal.Parse(criterios[1])
                    };

                    Ponderacion_Criterios criterio3 = new Ponderacion_Criterios
                    {
                        IdOferta = oferta.InformacionOferta.IdOferta,
                        IdCriterio = 3,
                        Ponderacion = decimal.Parse(criterios[2])
                    };

                    Ponderacion_Criterios criterio4 = new Ponderacion_Criterios
                    {
                        IdOferta = oferta.InformacionOferta.IdOferta,
                        IdCriterio = 4,
                        Ponderacion = decimal.Parse(criterios[3])
                    };

                    result3 += ponderacionModel.Insert(criterio1);
                    result3 += ponderacionModel.Insert(criterio2);
                    result3 += ponderacionModel.Insert(criterio3);
                    result3 += ponderacionModel.Insert(criterio4);

                    if ((result1 > 0) && (result2 > 0) && (result3 == 4))
                    {
                        TempData["successMessage"] = "Oferta laboral agregada de forma exitosa";
                        return RedirectToAction("Index");
                    }
                    else { 
                        TempData["errorMessage"] = "Upps! Ocurrió un error al agregar la nueva oferta laboral";
                    }
                }
                else
                {
                    TempData["errorMessage"] = "algun dato erróneo";
                }

                return View(oferta);
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message.ToString();
                return View(oferta);
            }
        }

        // GET: Ofertas/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                TempData["errorMessage"] = "Para modificar la información de una oferta de empleo selecciónela del listado";
                return RedirectToAction("Index");
            }

            OfertasEmpleo oferta = model.GetById(id);

            if(oferta == null)
            {
                TempData["errorMessage"] = "No se encontró la oferta de empleo que solicitó";
                return RedirectToAction("Index");
            }

            OfertaEmpleoCompleta ofertaCompleta = model.ObtenerOfertaCompleta(oferta);
            ViewBag.Criterios = ponderacionModel.ObtenerPonderaciones(id);
            return View(ofertaCompleta);
        }

        // POST: Ofertas/Edit/5
        [HttpPost]
        public ActionResult Edit(OfertaEmpleoCompleta oferta, string[] criterios)
        {
            int result1 = 0;
            int result2 = 0;
            int result3 = 0;
            
            try
            {
                if (ModelState.IsValid)
                {
                    if ((decimal.Parse(criterios[0]) + decimal.Parse(criterios[1]) + decimal.Parse(criterios[2]) + decimal.Parse(criterios[3])) != 100)
                    {
                        ViewBag.ErrorPonderacion = "La suma de las ponderaciones de los criterios debe ser igual al 100%";
                        return View(oferta);
                    }

                    if (oferta.InformacionOferta.fecha_fin <= oferta.InformacionOferta.fecha_inicio)
                    {
                        ViewBag.ErrorFechas = "La Fecha de finalización debe ser mayor a la fecha de paertura de la oferta";
                        return View(oferta);
                    }
                    //Creando objetos Ponderacion_Criterios para actualizar la información en la BDD
                    Ponderacion_Criterios criterio1 = new Ponderacion_Criterios
                    {

Work_Source/Views/Ofertas/Calificar.cshtml
@model Work_Source.Models.DetalleOfertasEmpleo

<section class="sign-up section-padding" id="download">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>
                    Evaluación de Candidato
                </h2>
            </div>
                <hr />
                <br />
            <div class="col-md-6">
                <h4>
                    Aspirante:
                    @foreach (var user in ViewBag.NombreUsuario)
                    {
                        <span style="margin-right:6px;">@user.nombres</span> <span>@user.apellidos</span>
                    }
                </h4>
            </div>
                <br />
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#fase1">Fase 1</a></li>
                    <li><a data-toggle="tab" href="#fase2">Fase 2</a></li>
                    <li><a data-toggle="tab" href="#fase3">Fase 3</a></li>
                    <li><a data-toggle="tab" href="#fase4">Fase 4</a></li>
                </ul>
                @using (Html.BeginForm())
                {
                <div class="tab-content">
                    <div id="fase1" class="tab-pane fade in active">
                        <div class="form-horizontal">
                            <h4>Cumplimiento de perfil de contratación</h4>
                            <hr />
                            <div class="form-group">
                                @Html.LabelFor(model => model.Criterio1, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Criterio1, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Criterio1, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="fase2" class="tab-pane fade in active">
                        <div class="form-horizontal">
                            <h4>Rendimiento en pruebas técnicas</h4>
                            <hr />
                            <div class="form-group">
                                @Html.LabelFor(model => model.Criterio2, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Criterio2, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Criterio2, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="fase3" class="tab-pane fade in active">
                        <div class="form-horizontal">
                            <h4>Resultados de pruebas psicológicas y conductuales</h4>
                            <hr />
                            <div class="form-group">
                                @Html.LabelFor(model => model.Criterio3, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Criterio3, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Criterio3, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="fase4" class="tab-pane fade in active">
                        <div class="form-horizontal">
                            <h4>Rendimiento en Entrevista</h4>
                            <hr />
                            <div class="form-group">
                                @Html.LabelFor(model => model.Criterio4, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Criterio4, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Criterio4, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                }
               
        </div>
    </div>
</section>

Work_Source/Views/Ofertas/Details.cshtml
@model Work_Source.Models.OfertasEmpleo

<section class="sign-up section-padding" id="download">
    <div class="container">
        <h3>Detalles de la Oferta</h3>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NombreOferta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NombreOferta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.estado)
            </dt>

            <dd>
                @(Model.estado.Equals(1) ? "Oferta Activa" : Model.estado.Equals(2) ? "Ofertas en proceso de selección" : "Oferta Finalizada")
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NombrePuesto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NombrePuesto)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MisionPuesto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MisionPuesto)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TipoContratacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TipoContratacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NumPlazas)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NumPlazas)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.salario)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.salario)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fecha_inicio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fecha_inicio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fecha_fin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fecha_fin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.detalles)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.detalles)
            </dd>

            <dt>
                Creador
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Usuarios.nombres)
            </dd>

        </dl>
        <br />
        <br />
        <div class="row">
            <div class="col-md-6">
                @Html.ActionLink("Editar Oferta", "Edit", new { id = Model.IdOferta }, new { @class = "btn btn-warning" }) |
                @Html.ActionLink("Listado de ofertas", "Index", null, new { @class= "btn btn-success" })
            </div>
        </div>
        <br /><br />
        <div class="row">
            <div class="col-md-6">
                <h4>Aplicantes de la oferta</h4>
                <hr />
            </div>
            <br /><br />
            <table class="table table-condensed table-hover table-stripped table-responsive">
                <thead>
                    <tr>
                        <th class="text-center">Nombres</th>
                        <th class="text-center">Apellidos</th>
                        <th class="text-center">Teléfono</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.DetalleOfertasEmpleo)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Usuarios.nombres)</td>
                            <td>@Html.DisplayFor(modelItem => item.Usuarios.apellidos)</td>
                            <td>@Html.DisplayFor(modelItem => item.Usuarios.telefono)</td>
                            <td>@Html.DisplayFor(modelItem => item.Usuarios.email)</td>
                            <td class="text-center">@Html.ActionLink("Seleccionar", "Calificar", new { IdUsuario = item.Usuarios.codigo, IdOferta = Model.IdOferta }, new { @class = "btn btn-primary" })</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        
    </div>
</section>
        
        
          
     
       

Work_Source/Views/Ofertas/Index.cshtml
@model PagedList.IPagedList<Work_Source.Models.OfertasEmpleo>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<section class="sign-up section-padding" id="download">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @Html.ActionLink("Agregar Oferta", "Create", null, new { @class = "btn btn-success" })
            </div>
        </div>
        <br /><br />
        <div class="row">
            @using (Html.BeginForm("Index","Ofertas", FormMethod.Post,new { @id="frmBusqueda", @onsubmit = "return validarDatos();" }))
            {
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-3">
                            <label class="control-label">Seleccione un criterio de búsqueda:</label>
                        </div>
                        @Html.Hidden("valorOculto", ViewBag.ValorOculto as string, new { @class = "form-control", @id = "valorOculto" })
                        @Html.Hidden("hfbusqueda", ViewBag.Busqueda as string, new { @class = "form-control", @id = "hfbusqueda" })
                        <div class="col-md-2">
                            <select class="form-control" id="seleccion" name="filtroBusqueda">
                                <option value="" disabled>-- Seleccione --</option>
                                <option value="Todos">Todos los resultados</option>
                                <option value="Nombre">Nombre de Oferta</option>
                                <option value="Creador">Creador de Oferta</option>
                                <option value="Estado">Estado de Oferta</option>
                                <option value="Fechas">Fecha de publicación</option>
                            </select>
                        </div>
                        <div class="col-md-3 text-danger" id="errorSeleccion">

                        </div>
                    </div>
                </div>
                <br /><br />
                <div class="row" id="caja">

                </div>
                <div class="row" id="creadores">
                    <div class="col-md-2">
                        <label class="control-label">
                            Creador de oferta de empleo:
                        </label>
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownList("busqueda", (SelectList)ViewBag.ListadoCreadores, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" name="Buscar" value="Buscar" class="btn btn-warning" />
                    </div>
                </div>
            }
        </div>
        <br /><br />
        <div class="row">
            <table class="table table-condensed table-hover table-stripped table-bordered table-responsive">
                <thead>
                    <tr>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.FirstOrDefault().NombreOferta)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.FirstOrDefault().creador)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().TipoContratacion)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.FirstOrDefault().fecha_inicio)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.FirstOrDefault().fecha_fin)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.FirstOrDefault().estado)
                        </th>
                        <th class="text-center">
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreOferta)
                            </td>
                            <td>
                                @(item.Usuarios.nombres + " " + item.Usuarios.apellidos)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoContratacion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.fecha_inicio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.fecha_fin)
                            </td>
                            <td>
                                @(item.estado.Equals(1) ? "Oferta Activa" : item.estado.Equals(2) ? "Oferta en proceso de selección" : "Oferta finalizada")
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id = item.IdOferta }, new { @class = "btn btn-primary" }) |
                                @Html.ActionLink("Detalles", "Details", new { id = item.IdOferta }, new { @class = "btn btn-warning" }) |
                                @Html.ActionLink("Eliminar", "Delete", new { id = item.IdOferta }, new { @class = "btn btn-danger",
                                @onclick = "return confirm('Desea eliminar el registro de ésta oferta laboral?');"
                           })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            <!--Controles de paginación-->
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page }))
        </div>
    </div>
</section>

Work_Source/Views/Ofertas/VerOfertas.cshtml
@model PagedList.IPagedList<Work_Source.Models.OfertasEmpleo>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<section class="sign-up section-padding" id="download">
    <div class="container">
        <br />
        <div class="row">
            @using (Html.BeginForm("VerOfertas", "Ofertas", FormMethod.Post))
            {
                <label class="control-label col-md-2">
                    Buscar por nombre de oferta:
                </label>
                <div class="col-md-3">
                    @Html.TextBox("txtBuscar", "", new { @class = "form-control" })
                </div>
                <label class="control-label col-md-2">
                    Estado de Oferta:
                </label>
                <div class="col-md-3">
                    @Html.DropDownList("estadoOferta", new List<SelectListItem>
               {
                   new SelectListItem { Value = "", Text = "Todas" },
                   new SelectListItem { Value = "1", Text = "Oferta Activa" },
                   new SelectListItem { Value = "2", Text = "En proceso de selección" },
                   new SelectListItem { Value = "3", Text = "Oferta Finalizada" }
               },
               new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    <input type="submit" value="Buscar" class="btn btn-warning"/>
                </div>
            }
        </div>
        <br />
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 intro-feature">
                    <div class="panel panel-default" style="max-width:500px;margin-left:auto;margin-right:auto;">
                        <div class="panel-heading">@item.NombreOferta</div>
                        <div class="panel-body">
                            <img src="img/work.jpg" width="200" height="150" />
                            <p>Puesto: @item.NombrePuesto</p>
                            <p>Tipo de Contratación: @item.TipoContratacion</p>
                            <p>Salario ofrecido: $ @item.salario</p>
                            <p>Cantidad de plazas: @item.NumPlazas</p>
                            <p>Estado: @(item.estado.Equals(1) ? "Oferta Activa" : @item.estado.Equals(2) ? "En proceso de selección" : "Oferta Finalizada")</p>
                            <div class="divider"></div>
                            @Html.ActionLink("Aplicar", "AplicarOferta", new { id = item.IdOferta }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            }
        </div>
        <br />
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("VerOfertas",
            new { page }))
    </div>
</section>